### ISSUE TITLE
[Enhancement] Clarifying paused/inactive skillqueues

### ISSUE THREAD

**Issue by jamiew0w** [cvweiss/skillq#52]
For example, this character;

![](https://imgs.ovh/i/xq0e1S.png)

Has a paused skillqueue in game;

![](https://imgs.ovh/i/d24223.png)

Would it be possible to have a clarification added stating 'Skillqueue paused' or 'Skillqueue empty' with a warning symbol (much like when the scopes are broken and need to be re-added).

Would be a nice QOL improvement.

**Comment by cvweiss** [comment]
This feature has been requested in the past, there's a couple issues with implementation:

* Identifying a character that _should_ be training vs a character that shouldn't be?
* Random alts vs mains, since we no longer have account level view of characters it isn't possible to tell if characters on an account are training or not. 
* The lack of a skill with a countdown is already visual indication that there is no skill training. Adding "no skill training" to every character with no training would get cumbersome on screens with many characters loaded that shouldn't be training.

Does anyone else have further thoughts on this?

**Comment by jamiew0w** [comment]
I've been thinking about this quite a bit over the last few days. I like the current layout how you can split characters into different groups so maybe an option may be adding a second 'view' where you can manually add characters to accounts much like the current system. 

For example, at the top there's the 'All' tab, maybe adding one named 'Accounts' where there's a similar setup to the 'Manage' page, you just add your 1,2,3 chars to account and then a check to see if there's at least 1 char in this group learning. A tickbox to add MTCs to characters would be neat, but I'm not sure if I'm just overthinking it and making it too awkward. That should help with your first 2 bullet points and I agree on the third one too.
